version: "3.1"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    container_name: orm_example
    volumes:
      - ./database:/var/lib/mysql
