version: "3"

services:
  node:
    image: node:16
    container_name: cep_lookup_node
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db

  db:
    container_name: cep_lookup
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
