version: '3'

services:
  db:
    container_name: meuMySQL
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=Trybe2022!
      - MYSQL_USER=Tryber
      - MYSQL_PASSWORD=tryber19
    restart: always
    volumes:
      - /home/mauro/Documents/Trybe/Back_End/bloco-20-introducao-a-sql/data:/var/lib/mysql